[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.intl",
  "php83Extensions.zip",
  "php83Extensions.mbstring",
  "php83Extensions.pdo_mysql",
  "php83Extensions.tokenizer"
]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-interaction --no-scripts"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
